# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1_provided_sp24/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_final/mb_final.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final || ORIG_REF_NAME==mb_final} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_0/mb_final_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_0 || ORIG_REF_NAME==mb_final_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_dlmb_v10_0/mb_final_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_dlmb_v10_0 || ORIG_REF_NAME==mb_final_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_ilmb_v10_0/mb_final_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_ilmb_v10_0 || ORIG_REF_NAME==mb_final_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_dlmb_bram_if_cntlr_0/mb_final_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_final_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_ilmb_bram_if_cntlr_0/mb_final_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_final_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_lmb_bram_0/mb_final_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_lmb_bram_0 || ORIG_REF_NAME==mb_final_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_xbar_0/mb_final_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_xbar_0 || ORIG_REF_NAME==mb_final_xbar_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_axi_periph_0/mb_final_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_final_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_axi_intc_0/mb_final_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_final_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_xlconcat_0/mb_final_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_final_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_mdm_1_0/mb_final_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_mdm_1_0 || ORIG_REF_NAME==mb_final_mdm_1_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_clk_wiz_1_0/mb_final_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_clk_wiz_1_0 || ORIG_REF_NAME==mb_final_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_rst_clk_wiz_1_100M_0/mb_final_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_final_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_uartlite_0_0/mb_final_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_uartlite_0_0 || ORIG_REF_NAME==mb_final_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_gpio_0_0/mb_final_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_gpio_0_0 || ORIG_REF_NAME==mb_final_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_gpio_0_1/mb_final_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_gpio_0_1 || ORIG_REF_NAME==mb_final_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_gpio_0_2/mb_final_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_gpio_0_2 || ORIG_REF_NAME==mb_final_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_timer_0_0/mb_final_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_timer_0_0 || ORIG_REF_NAME==mb_final_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_quad_spi_0_0/mb_final_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_final_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/mb_final_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_final_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/mb_final_ooc.xdc
