# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Taowei/Documents/ECE385/final_project/final_project.srcs/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/mb_final_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_final_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/final_rom_dis/final_rom_dis.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_rom_dis || ORIG_REF_NAME==final_rom_dis} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/text_rom/text_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==text_rom || ORIG_REF_NAME==text_rom} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/final_rom_dis/final_rom_dis_ooc.xdc

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/text_rom/text_rom_ooc.xdc

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/Users/Taowei/Documents/ECE385/final_project/final_project.srcs/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/mb_final_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_final_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/final_rom_dis/final_rom_dis.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_rom_dis || ORIG_REF_NAME==final_rom_dis} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/text_rom/text_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==text_rom || ORIG_REF_NAME==text_rom} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/final_rom_dis/final_rom_dis_ooc.xdc

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/text_rom/text_rom_ooc.xdc

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/Taowei/Documents/ECE385/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
